version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
      - "9229:9229"
    depends_on:
      - migrate
    volumes:
      - .:/usr/src/app
    environment:
      - PORT=4000
      - DATABASE_URL=postgresql://myuser:mypassword@postgres:5432/mydatabase

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  migrate:
    build: 
      context: .
      dockerfile: Dockerfile
    command: npx prisma migrate deploy
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@postgres:5432/mydatabase

volumes:
  pgdata:
